### ISSUE TITLE
Eslint can't recognise nullish coalescing operator with `plugin:n/recommended`

### ISSUE THREAD

**Issue by anantakrishna** [eslint-community/eslint-plugin-n#73]
"eslint": "8.24.0"
"eslint-plugin-n": "15.6.0"

`.eslintrc.yml`:
```YAML
root: true
env:
  node: true
  es2021: true
parserOptions:
  sourceType: module
extends:
  - eslint:recommended
  - plugin:n/recommended
  - prettier
```

`package.json`:
```
  "engines": {
    "node": "16"
  },
```

VSCode shows the following error for nullish coalescing operator:
> Parsing error: Unexpected token ?

![image](https://user-images.githubusercontent.com/6065071/205993245-0e8376ab-47c7-4be4-a59e-08adc474f548.png)

According to node.green, this operator is supported in Node v16: https://node.green/#ES2020-features--nullish-coalescing-operator-----

Running eslint with `--print-config` shows:

```
"ecmaVersion": 2019
```

Perhaps, this is the cause. But why is it 2019?

Disabling `plugin:n/recommended` removes the above mentioned eslint error, but it brings back another error about [instance class fields](https://node.green/#ES2022-features-instance-class-fields), which is part of ES2022. This feature is supported by Node v16, but I can't specify `"ecmaVersion": 2022` because Node v16 does not support it fully. This was my motivation for using `eslint-plugin-n`.
